.de FN
\fI\|\\$1\|\fP\\$2
..
.TH ii 1
.SH NAME
ii \- irc it or irc improved

.SH DESCRIPTION
.B ii
is a minimalistic FIFO and filesystem based IRC client. It creates an IRC
directory tree with server, channel and nickname directories. In every
directory a FIFO file (in) and a normal file (out) is placed. This will be for
example in irc/irc.freenode.net/. The in file is used to communicate with the
servers and the out files include the server messages. For every channel and
every nickname, there will be a new in and out file. The idea of this is to be
able to communicate with an IRC server using basic command line tools.  For
example if you want to join a channel, just echo "/j #channel" > in and ii
will create a new channel directory with an in and out file inside it.

.SH SYNOPSIS
.B ii
.RB [ \-s
.IR servername ]
.RB [ \-p
.IR port ]
.RB [ \-k
.IR password ]
.RB [ \-i
.IR prefix ]
.RB [ \-n
.IR nickname ]
.RB [ \-f
.IR realname ]
.RB [ \-d
.IR directory ]

.SH OPTIONS
.TP
.BI \-s " servername"
Lets you override the default servername. (irc.freenode.net)
.TP
.BI \-p " port"
Lets you override the default port. (6667)
.TP
.BI \-k " password"
Lets you use a password to authenticate your nickname on the server. (Be aware
of the problem that this is visible in the process list. If you don't want
this, then simply use a query to submit your password.)
.TP
.BI \-i " prefix"
Lets you override the default IRC path. (irc)
.TP
.BI \-n " nickname"
Lets you override the default nickname. (anonymous)
.TP
.BI \-f " realname"
Lets you specify your real name associated with your nickname.
.TP
.BI \-d " directory"
Lets you override the servername part in the directory tree structure. Useful
with the wrapper program as the servername then might change.

.SH DIRECTORIES
.TP
.FN irc
In this directory the IRC tree will be created and inside it you will find a
directory for your server (default: irc.freenode.net) in which the FIFO and the
output file will be stored. If you join a channel, a new directory with the
name of it will be created in the irc/$servername/ directory. ($servername can
be overridden with $directory.)

.SH COMMANDS
Everything which is not a command, will simply be posted into the channel or to
the server. So if you need /who just write /WHO as described in the RFC to the
in FIFO file of the server.
.TP
.FN /j " #channel/nickname [<message>]"
Join a channel or open a private conversation with another user.
.TP
.FN /l " #channel/nickname [<message>]"
Leave a channel or query.
.TP
.FN /n " nickname"
Change the nickname.
.TP
.FN /t " topic"
Set the topic of a channel.
.TP
.FN "out file usage"
Write wrappers, pagers or use your tools of choice to display the out file
contents (loco, multitail, etc.). 
.SH CONTACT
.TP
Write to ii (at) modprobe (dot) de for suggestions, fixes, 7|-|>< ;) etc.
.SH AUTHORS
Copyright \(co 2005-2006 by Anselm R. Garbe <garbeam (at) gmail (dot) com> and 
Copyright \(co 2005-2008 by Nico Golde <nico (at) ngolde (dot) de>
.SH SEE ALSO
.BR echo (1),
.BR tail (1)
